[Bug 8692]:  Improving te_repack_raw_logs script interface
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@93110 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/tools/rgt/rgt-log-bundle/te_repack_raw_logs b/tools/rgt/rgt-log-bundle/te_repack_raw_logs
--- a/tools/rgt/rgt-log-bundle/te_repack_raw_logs
+++ b/tools/rgt/rgt-log-bundle/te_repack_raw_logs
@@ -4,16 +4,48 @@ export TMPDIR="${TMPDIR:-/tmp}"
 
 set -e
 
-if test x"$*" = x -o x"$1" = x"--help" -o x"$1" = x"-h" ; then
+usage()
+{
     cat <<EOF
 Repacking existing raw logs in specified directories and their subdirs:
 log.raw.bz2 -> raw_log_bundle.tpxz
-Usage: repack_raw_logs dir_path1 [dir_path2 dir_path3 ... dir_pathN]
+Usage: repack_raw_logs [options] dir_path1 [dir_path2 dir_path3 ... dir_pathN]
 Environment variables:
     TMPDIR          Directory for temporary files (/tmp/ if not set)
     PATH            Should include path to TE scripts and tools
 EOF
-    exit 0
+}
+
+repack_existing=yes
+remove_original=no
+
+while test -n "$1" ; do
+    case "$1" in
+        --help ) usage ; exit 0 ;;
+        -h )     usage ; exit 0 ;;
+        --repack-existing=* ) repack_existing="${1#--repack-existing}" ;;
+        --remove-original=* ) remove_original="${1#--remove-original}" ;;
+        *) break ;;
+    esac
+    shift 1
+done
+
+if test x"$*" = x ; then
+    echo "Path(s) were not specified" 2>&1
+    usage
+    exit 1
+fi
+if test x"${repack_existing}" != x"no" -a \
+        x"${repack_existing}" != x"yes" ; then
+    echo "--repack-existing may be only 'yes' or 'no'" 2>&1
+    usage
+    exit 1
+fi
+if test x"${remove_original}" != x"no" -a \
+        x"${remove_original}" != x"yes" ; then
+    echo "--remove-original may be only 'yes' or 'no'" 2>&1
+    usage
+    exit 1
 fi
 
 raw_from_bz2=
@@ -90,7 +122,8 @@ process_raw_logs()
             echo "REPACK ERROR: Failed to " \
                  "determine directory of '${file_name}'" 2>&1
         else
-            if test -f "${log_dir}/raw_log_bundle.tpxz" ; then
+            if test x"${repack_existing}" = x"no" -a \
+                    -f "${log_dir}/raw_log_bundle.tpxz" ; then
                 echo "Raw log bundle already exists"
 
                 check_bundle "${log_dir}" && rc=0 || rc=1
@@ -98,10 +131,12 @@ process_raw_logs()
                     echo "REPACK ERROR: existing bundle does " \
                          "not match existing log.raw.bz2" 2>&1
                 else
-                    rm "${file_name}" && rc=0 || rc=1
-                    if test $rc -ne 0 ; then
-                        echo "REPACK ERROR: Failed " \
-                             "to delete '${file_name}'" 2>&1
+                    if test x"${remove_original}" = x"yes" ; then
+                        rm "${file_name}" && rc=0 || rc=1
+                        if test $rc -ne 0 ; then
+                            echo "REPACK ERROR: Failed " \
+                                 "to delete '${file_name}'" 2>&1
+                        fi
                     fi
                 fi
             else
@@ -116,10 +151,12 @@ process_raw_logs()
                     # as raw log unpacked from log.raw.bz2, so there is
                     # no point to redo this check here
 
-                    rm "${file_name}" && rc=0 || rc=1
-                    if test $rc -ne 0 ; then
-                        echo "REPACK ERROR: Failed to " \
-                             "delete '${file_name}'" 2>&1
+                    if test x"${remove_original}" = x"yes" ; then
+                        rm "${file_name}" && rc=0 || rc=1
+                        if test $rc -ne 0 ; then
+                            echo "REPACK ERROR: Failed to " \
+                                 "delete '${file_name}'" 2>&1
+                        fi
                     fi
                 fi
             fi
