fixed behaviour on non-existent files
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@20002 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/tools/tce/tce_kallsyms b/tools/tce/tce_kallsyms
--- a/tools/tce/tce_kallsyms
+++ b/tools/tce/tce_kallsyms
@@ -3,6 +3,11 @@
 for mfile in "$@"; do
     module=`basename $mfile .ko`
     offset=`grep ^$module' ' /proc/modules | awk '{ print $NF }'`
-    nm $mfile | grep -i gcov | 
-    awk -vmodule=$module '{ printf "%8.8x %s %s %s [%s]\n", strtonum('$offset') + strtonum("0x" $1), $2, $3, $4, module }'
+    if test -z "$offset"; then
+        echo "Module $module not found" >&2 
+    else
+        nm $mfile | grep -i gcov | 
+        awk -vmodule=$module -voffset=$offset \
+            '{ printf "%8.8x %s %s %s [%s]\n", strtonum(offset) + strtonum("0x" $1), $2, $3, $4, module }'
+    fi
 done
