added check for non-existing infile
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@20233 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/tools/tce/tce_report b/tools/tce/tce_report
--- a/tools/tce/tce_report
+++ b/tools/tce/tce_report
@@ -96,6 +96,10 @@ if test -z "`which tce_merge`" ; then
     fi
 fi
 
+if ! test -f $infile; then
+    echo "$infile not found" >&2
+    exit 1
+fi
 
 # cleanup files that might remain from previous sessions
 for pattern in '*.gcov' '*.da' '*.gcda' '.[a-z]*.da' '.[a-z]*.gcda'; do
