[Bug 432]:  FIXED tce_report now works if its supporting utilities are not in PATH but in its directory
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@15871 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/engine/builder/tce_report b/engine/builder/tce_report
--- a/engine/builder/tce_report
+++ b/engine/builder/tce_report
@@ -22,6 +22,17 @@ HELP
     exit 1
 fi
 
+binaries="`which tce_merge`"
+if test -z "$binaries"; then
+    mydir=`dirname $0`
+    if test -x ${mydir}/tce_merge; then
+        export PATH=${mydir}:$PATH
+    else
+        echo "Supporting scripts not found!!!" >/dev/stderr
+        exit 1
+    fi
+fi
+
 tce_taname=$1 
 mergefile=$2
 outfile=${mergefile}.new
