Debugging 64-bit build...
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@26265 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/engine/builder/te_build_win_app b/engine/builder/te_build_win_app
--- a/engine/builder/te_build_win_app
+++ b/engine/builder/te_build_win_app
@@ -42,54 +42,23 @@ LIBS=$4
 LIBS=`eval "echo "$LIBS`
 shift 4
 
+. `dirname $0`/te_build_win_platform
 
-BUILDDIR=`pwd`
+WIN_DIR=${USER}_build/${APPNAME%%.exe}
 
-WIN_DIR=${USER}_build_${APPNAME%%.exe}
+if test -z "$TE_WIN32_BUILD_HOST" -o ! -d ${TE_INSTALL}/${PLATFORM} ; then
+    exit 0
+fi    
+
+if ! ssh $KEY $TE_WIN32_BUILD_HOST \
+         "rm -rf $WIN_DIR; mkdir -p $WIN_DIR" >/dev/null; then
+    echo "Error: build host $TE_WIN32_BUILD_HOST is unreachable"
+    exit 1
+fi
+
+rm -f ${APPNAME}
 
 rm -rf tmpsrc
-
-if test $PLATFORM != ${PLATFORM#x86_64} ; then
-
-BUILD_HOST=${TE_WIN64_BUILD_HOST}
-KEY=${TE_WIN64_BUILD_HOST_KEY}
-ADD_CMD='export PATH=`cygpath -u \"\$MSSDK\bin\win64\x86\AMD64\"`:\$PATH ; \
-if test -n \"\$MSSDK\" ; then \
-export LIB=\"\$MSSDK\lib\AMD64;\$MSSDK\lib\AMD64\atlmfc;\$MSSDK\lib;\
-C:\WINDDK\3790.1830\lib\wnet\amd64\" ; fi ;'
-ADD_LIB="bufferoverflowU.lib"
-
-else
-
-BUILD_HOST=${TE_WIN32_BUILD_HOST}
-KEY=${TE_WIN32_BUILD_HOST_KEY}
-ADD_CMD=
-ADD_LIB=
-PDB="/Zi"
-
-fi
-
-if test -z "$BUILD_HOST" ; then
-    exit 0
-fi    
-
-if test -n "$KEY" ; then
-    KEY="-i $KEY "
-fi    
-
-if ! ssh $KEY $BUILD_HOST ls >/dev/null; then
-    exit 0
-fi
-
-ssh $KEY ${BUILD_HOST} "rm -rf ${WIN_DIR}; mkdir -p ${WIN_DIR}/tmpsrc"
-
-# Copy libraries and headers to the build host
-cd ${TE_INSTALL}
-tar czf ${BUILDDIR}/${PLATFORM}.tgz ${PLATFORM}
-cd ${BUILDDIR}
-scp $KEY ${PLATFORM}.tgz ${BUILD_HOST}:${WIN_DIR}
-rm ${PLATFORM}.tgz
-
 mkdir tmpsrc
 
 # Apply pre-processor to application files
@@ -110,31 +79,36 @@ for i in $* ; do
     rm ${FILENAME}.tmp ; 
     indent tmpsrc/${FILENAME} ;
 done
+ln -s ${TE_INSTALL}/${PLATFORM} ${PLATFORM}
 
+# Generate the script
+cat >build.sh <<EOF
+MSSDK_CYGWIN_BAD=\$( cygpath -u \$MSSDK ) 
+MSSDK_CYGWIN="\`echo \$MSSDK_CYGWIN_BAD\`"
+export PATH="\${MSSDK_CYGWIN}/Bin$PATH_POSTFIX:\$PATH"
+export LIB="\${MSSDK}\Lib$LIB_POSTFIX;\$LIB"
+rm src.tgz
+cd tmpsrc 
+cl -I../${PLATFORM}/include -DWINDOWS -D_CRT_SECURE_NO_DEPRECATE \
+   -D_WIN32_WINNT=0x0501 /w /Zi *.c \
+   /link /OUT:${APPNAME} /MAP /LIBPATH:../${PLATFORM}/lib \
+   ${LIBS} ${ADD_LIB} 
+EOF
+chmod a+x build.sh
+
+tar czhf src.tgz tmpsrc ${PLATFORM} build.sh
 
 # Build the application
 
-scp $KEY tmpsrc/*.c ${BUILD_HOST}:${WIN_DIR}/tmpsrc
-rm -rf tmpsrc 
+scp $KEY src.tgz ${TE_WIN32_BUILD_HOST}:${WIN_DIR}
+rm -rf src.tgz tmpsrc ${PLATFORM} build.sh
 
-ssh $KEY ${BUILD_HOST} bash -l -c "\"
-$ADD_CMD \
-cd ${WIN_DIR} ; \
-tar xzf ${PLATFORM}.tgz ; \
-rm ${PLATFORM}.tgz ; \
-cd tmpsrc ; \
-cl /nologo -I../${PLATFORM}/include -DWINDOWS -D_CRT_SECURE_NO_DEPRECATE \
-   -D_WIN32_WINNT=0x0501 ${PDB} *.c \
-   /link /OUT:${APPNAME} /MAP /LIBPATH:../${PLATFORM}/lib \
-   ${LIBS} ${ADD_LIB} ; 
-cd ../.. ; \
-tar czf ${WIN_DIR}.tgz ${WIN_DIR} \""
+ssh $KEY ${TE_WIN32_BUILD_HOST} \
+"bash -l -c \"cd $WIN_DIR ; tar xzf src.tgz ; ./build.sh\""
 
-scp $KEY ${BUILD_HOST}:${WIN_DIR}/tmpsrc/${APPNAME} .
-scp $KEY ${BUILD_HOST}:${WIN_DIR}.tgz .
+scp $KEY ${TE_WIN32_BUILD_HOST}:${WIN_DIR}/tmpsrc/${APPNAME} .
 
 if test -e ${APPNAME} ; then
-    ssh $KEY ${BUILD_HOST} "rm -rf ${WIN_DIR} ${WIN_DIR}.tgz"
     exit 0
 fi
 
