[Bug 8526]:  New feature building over ssh has been added.
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@90616 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/engine/builder/te_configure_package b/engine/builder/te_configure_package
--- a/engine/builder/te_configure_package
+++ b/engine/builder/te_configure_package
@@ -32,6 +32,7 @@
 . builder.conf.processed
 
 SCRIPT_DIR=`dirname $0`
+. ${SCRIPT_DIR}/te_functions
 
 KIND=$1
 PACKAGE=$2
@@ -67,9 +68,12 @@ configure_package()
 
     echo ${PKGSRC}/configure -q --prefix=$PREFIX ${PARMS}
 
-    TE_DEPENDENCIES="$DEPENDENCIES" \
-    CFLAGS= \
-    eval ${PKGSRC}/configure '-q --prefix=$PREFIX' ${PARMS}
+    te_eval_or_ssh "${PLATFORM}" "
+        export TE_EXT_LIBS_FILE=\"$TE_EXT_LIBS_FILE\"
+        TE_DEPENDENCIES='$DEPENDENCIES' \\
+        CFLAGS= \\
+        ${PKGSRC}/configure -q --prefix=$PREFIX ${PARMS}
+    "
 }
 
 # Create list of linked libraries and dependencies for the package
@@ -115,8 +119,13 @@ mkdir -p $PKGBUILDDIR ;
 cd $PKGBUILDDIR ;
 
 if test -e Makefile ; then
-    make install-data || exit 1
-    exit 0
+# Code "echo=echo" was added, for bug fixing of a look "X--tag=CC: command not found"
+# See https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00011.html
+    te_eval_or_ssh "${PLATFORM}" "
+        echo=echo \\
+        make install-data || exit 1
+    "
+    exit $?
 fi
 
 if test ! -e ${PKGSRC}/configure ; then
@@ -172,6 +181,10 @@ if test $? -ne 0 ; then
     fi
 fi
 
-make install-data || exit 1
-
-exit 0
+# Code "echo=echo" was added, for bug fixing of a look "X--tag=CC: command not found"
+# See https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00011.html
+te_eval_or_ssh "${PLATFORM}" "
+    echo=echo \\
+    make install-data || exit 1
+"
+exit $?
diff --git a/engine/builder/te_cross_build b/engine/builder/te_cross_build
--- a/engine/builder/te_cross_build
+++ b/engine/builder/te_cross_build
@@ -30,6 +30,9 @@
 
 . builder.conf.processed
 
+SCRIPT_DIR=`dirname $0`
+. ${SCRIPT_DIR}/te_functions
+
 PREFIX=$1
 DUMMY=
 
@@ -52,9 +55,15 @@ for p in ${TE_BS_PLATFORMS} ; do
             $PREFIX || exit 1
     done
     for package in $LIBS ; do
-        pushd ${TE_BUILD}/platforms/${p}/lib/$package >/dev/null
-        make ${BUILD_MAKEFLAGS} install || exit 1
-        popd >/dev/null
+# Code "echo=echo" was added, for bug fixing of a look "X--tag=CC: command not found"
+# See https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00011.html
+        te_eval_or_ssh "${p}" "
+            pushd ${TE_BUILD}/platforms/${p}/lib/$package >/dev/null
+            echo=echo \\
+            make ${BUILD_MAKEFLAGS} install || exit 1
+            popd >/dev/null
+        "
+        res=$?; if test "$res" -ne "0" ; then exit $res; fi
     done
 done
 
@@ -67,9 +76,15 @@ for package in $DUMMY $TE_BS_TA ; do
     fi
     ${TE_BASE}/engine/builder/te_configure_package TA $package $package \
         $package $PLATFORM $PKGSRC $PREFIX || exit 1
-    cd agents/$package
-    make ${BUILD_MAKEFLAGS} install || exit 1
-    cd ../..
+# Code "echo=echo" was added, for bug fixing of a look "X--tag=CC: command not found"
+# See https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00011.html
+    te_eval_or_ssh "TE_BS_TA_${PLATFORM}" "
+        cd agents/$package
+        echo=echo \\
+        make ${BUILD_MAKEFLAGS} install || exit 1
+        cd ../..
+    "
+    res=$?; if test "$res" -ne "0" ; then exit $res; fi
 done
 
 exit 0
