engine/builder: improve syncing of build directories
Ensure that local and remote build directories are fully synchronized
by using --delete-during option not only when synchronizing remote
build with local build before building, but also when synchronizing
in opposite direction after building on remote host. Otherwise
some files from previous build attempts may preserve in local build
folder indefinitely, even when source code or build configuration
changes between build attempts so that these files should no longer
be present.

OL-Redmine-Id: 12270
Signed-off-by: Dmitry Izbitsky <dmitry.izbitsky@oktetlabs.ru>
Reviewed-by: Andrew Rybchenko <andrew.rybchenko@oktetlabs.ru>

diff --git a/engine/builder/te_cross_build_meson b/engine/builder/te_cross_build_meson
--- a/engine/builder/te_cross_build_meson
+++ b/engine/builder/te_cross_build_meson
@@ -16,13 +16,14 @@ SCRIPT_DIR="$(dirname "$0")"
 declare -a RSYNC
 RSYNC+=(rsync)
 RSYNC+=(-a)
+RSYNC+=(--delete-during)
+
 if test -n "$BUILDER_DEBUG" ; then
      RSYNC+=("-vv")
      RSYNC+=("-stat")
 fi
 
 declare -a RSYNC_TO_ARGS
-RSYNC_TO_ARGS+=(--delete-during)
 RSYNC_TO_ARGS+=(--delete-excluded)
 # External libraries may contain symlinks outside of build
 # root and may be unavailable on the target build host.
@@ -427,11 +428,20 @@ build_platform() {
                 error "Sync install from remote failed"
 
             # Get installed agents
-            te_eval_or_ssh "${p}" \
-                "test ! -d \"${ws}/destdir/${te_agents}\"" ||
-            rsync_from "${p}" "${ws}/destdir/${te_agents}"/ \
-                "${te_agents}" ||
-                error "Sync agents from remote failed"
+            declare -a agents
+            agents+=($(te_eval_or_ssh "${p}" \
+                       "ls \"${ws}/destdir/${te_agents}\" 2>/dev/null")) \
+              || true
+
+            # rsync_from should be called for every agent subdirectory
+            # instead of calling it once for parent directory because
+            # otherwise it can remove agents of other platforms due to
+            # --delete-during option.
+            for agt in "${agents[@]}" ; do
+                rsync_from "${p}" "${ws}/destdir/${te_agents}/${agt}"/ \
+                    "${te_agents}/${agt}" ||
+                    error "Sync $agt from remote failed"
+            done
         fi
     fi
 
