[Bug 8526]:  Do not require to call 'bootstrap.sh' after large changes
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@91308 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/engine/builder/te_configure_package b/engine/builder/te_configure_package
--- a/engine/builder/te_configure_package
+++ b/engine/builder/te_configure_package
@@ -118,14 +118,17 @@ fi
 mkdir -p $PKGBUILDDIR ;
 cd $PKGBUILDDIR ;
 
-if test -e Makefile ; then
+# If the file 'Makefile' exists and its update was successful (auto start
+# autotools on the local machine), then we run 'make'
+if test -e Makefile && make Makefile ; then
 # Code "echo=echo" was added, for bug fixing of a look "X--tag=CC: command not found"
 # See https://lists.gnu.org/archive/html/bug-libtool/2008-04/msg00011.html
     te_eval_or_ssh "${PLATFORM}" "
         echo=echo \\
         make install-data || exit 1
     "
-    exit $?
+    exit $? # 'Makefile' is up to date. We can get out from here without
+            # doing 'autotool', 'configure' etc.
 fi
 
 if test ! -e ${PKGSRC}/configure ; then
@@ -169,7 +172,9 @@ fi
 
 configure_package
 
-if test $? -ne 0 ; then
+# If the file 'Makefile' could not create or update fails,
+# then we try to perform 'autotool'
+if test $? -ne 0 || ! make Makefile ; then
     if test x${TE_NO_AUTOTOOL} != "xyes" ; then
         autotool
         configure_package
