[Bug 8607]:  Add a recursive Makefiles update
git-svn-id: https://svn.oktetlabs.ru/svnroot/prj/oktetlabs/test-environment/src/trunk@91947 9d14d920-75d5-0310-8bd7-a52572981aee

diff --git a/engine/builder/te_functions b/engine/builder/te_functions
--- a/engine/builder/te_functions
+++ b/engine/builder/te_functions
@@ -168,3 +168,17 @@ te_is_in_list() {
     done
     return 1
 }
+
+##
+# Recursively update Makefiles
+#
+# @param $1     Directory name
+#
+# @return exit code from @b make
+#
+recursive_update_makefiles() {
+    local filename="$TE_BASE/auxdir/Makefile.update"
+    make -C "$1" MASTER_FILE=Makefile MAKEFILE_UPDATE="$filename" \
+        -f "$filename" update-recursive
+    return $?
+}
