scripts: make it clear if logs are not published
Add error logging to cleanup trap in the case of failure.

Signed-off-by: Andrew Rybchenko <andrew.rybchenko@oktetlabs.ru>
Reviewed-by: Dmitry Izbitsky <dmitry.izbitsky@oktetlabs.ru>
Reviewed-by: Artem Andreev <artem.andreev@oktetlabs.ru>

diff --git a/scripts/publish_logs b/scripts/publish_logs
--- a/scripts/publish_logs
+++ b/scripts/publish_logs
@@ -23,6 +23,7 @@ error() {
 #   tar_dir
 #####################################################################
 cleanup() {
+    [[ $? == 0 ]] || echo "${0}: Failed to publish logs" >&2
     trap '' EXIT ERR
     if [[ -n "${tar_dir}" ]] ; then
         rm -r "${tar_dir}"
